### ISSUE TITLE
Question about FLOP_COST

### ISSUE THREAD

**Issue by airzs** [COMP6248-Reproducability-Challenge/Differentiables_FastAccurateTextClassification#1]
why is the FLOP_COST in the code a constant value?

**Comment by ankursharma319** [comment]
Hi, 

This was an assumption stated in the paper https://openreview.net/pdf?id=ryZ8sz-Ab

On page 3 :

"the normalized FLOP count used at each time
step which is approximately constant."

The paper also stated that "that the FLOP count for the last step, Ft, differs, since
it also includes the cost of the classification"

We guessed this would be an insignificant difference and further made the assumption that the FLOP count for last time step was also approximately constant,  to simplify our code.

Hope this helped!

Kind Regards,
Ankur

**Comment by airzs** [comment]
Thanks for your clarification, which helped
